@startuml uc2 diagram 

actor "Gebruiker" as user
actor "Werkgever" as wg
actor "Bank" as b
actor "Overheid" as o

rectangle SSI {
  left to right direction
  usecase "Sluit hypotheek af" as UC2
}

user --> UC2 : toont identiteit, arbeidsovereenkomst
UC2 <-- b : vereist arbeidsovereenkomst, identiteit
wg <-- UC2 : verschaft arbeidsovereenkomst
UC2 <-- o : Verschaft identiteit

@enduml
