@startuml layer diagram
package "presentation/interaction layer" as pil {
  [webapp] as wap
  [mobile app] as map
}

package "service layer" as sl {
  [api]
  [mobile app backend] as mab
}

package "data layer" as dl {
  database database
}


wap --> api : https
map -> mab : method calls
api -> database : postgres protocol
api -> mab : https
@enduml
