@startuml deployment diagram
node server {
  [proxy]
  [webapp server] as was
  [api]
  [websocket server] as wss
  database data
}

[webapp]
:externepartij:

:Holder: as holder
:verifier: as verifier


' Mobile holder/verifier connection
holder <=> verifier : "WebSocket (via server)"

cloud "Root certificate" {
  artifact "Root certificate" as rootcert
}

rootcert => verifier

' App download
cloud github {
  artifact "user app download" as appdl
}

appdl --> holder
appdl -> verifier

' Connections to proxy
webapp => proxy : https
holder ===> proxy
externepartij ==> proxy : https



' Inside server block
proxy <-> was : http
proxy <--> api : http
api <-> data : database protocol
proxy <--> wss : WebSocket
@enduml

