@startuml layer diagram
package "presentation/interaction layer" as pil {
  [mobile app] as map
  [webapp] as wap
}

package "service layer" as sl {
  [api]
  [mobile app backend] as mab
}

package "data layer" as dl {
  database "central database" as cdb
  database "mobile database" as ldb
}

map -> mab : method calls
mab -> mab : Websockets

wap --> api : https

api --> cdb : postgres protocol
mab --> api : https
mab --> ldb : Room ORM
@enduml
